repository_type: pipeline
lint:
  files_exist:
    - assets/nf-core-genomeassembly_logo_light.png
    - docs/images/nf-core-genomeassembly_logo_light.png
    - docs/images/nf-core-genomeassembly_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
  files_unchanged:
    - .github/workflows/linting.yml
    - .github/CONTRIBUTING.md
    - LICENSE
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - assets/sendmail_template.txt
    - lib/NfcoreTemplate.groovy
    - .prettierignore
  nextflow_config:
    - manifest.name
    - manifest.homePage
  multiqc_config:
    - report_comment
  actions_ci:
    - .github/workflows/ci.yml
